#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
T4C Server Linux Migration Tool: Regional NPC Symbol Renamer
-----------------------------------------------------------
Description:
    Generates C++ header redirection (macros) to prevent symbol 
    collisions during monolithic linkage of regional NPCs.
    Replaces regional duplicates with unique prefixed symbols.

Authors:
    Developed by Tom [tlloancy] with the assistance of Cursor AI.
    Part of the T4C Server Linux Final Step project (2026).

License:
    MIT License - Feel free to use and modify for porting purposes.
-----------------------------------------------------------
"""
"""Emit per-region cpp macros so MonsterStatSetup globals link uniquely on Linux."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "T4C Server" / "linux_npc_region"
OUT_DIR.mkdir(parents=True, exist_ok=True)

REGIONS = [
    ("GameOps", "GameOps"),
    ("NPCs", "NPCs"),
    ("NPC AddOn", "NPCAddOn"),
    ("NPC Arakas", "Arakas"),
    ("NPC RavensDust", "RavensDust"),
    ("NPC Remort", "Remort"),
    ("NPC Stoneheim", "Stoneheim"),
    ("NPC WindHowl", "WindHowl"),
]

# Allow trailing whitespace / comments after `;`
PAT = re.compile(r"^\s*NPCstructure::NPC\s+(\w+)\s*;")


def main() -> None:
    for folder, sym in REGIONS:
        mss = ROOT / folder / "MonsterStatSetup.cpp"
        text = mss.read_text(encoding="utf-8", errors="replace")
        names = []
        for line in text.splitlines():
            m = PAT.match(line)
            if m:
                names.append(m.group(1))
        guard = f"T4C_LINUX_NPC_REGION_{sym.upper()}_RENAME_H"
        lines = [
            f"#ifndef {guard}",
            f"#define {guard}",
            "// Generated by tools/gen_linux_npc_region_rename.py — do not edit.",
            "",
        ]
        for n in names:
            lines.append(f"#define {n} {sym}_{n}")
        lines.extend(["", "#endif", ""])
        out = OUT_DIR / f"{sym}_rename.h"
        out.write_text("\n".join(lines), encoding="utf-8")
        print(f"Wrote {out.relative_to(ROOT)} ({len(names)} symbols)")


if __name__ == "__main__":
    main()
